// Objective-C API for talking to kit Go package.
//   gobind -lang=objc kit
//
// File is generated by gobind. Do not edit.

#ifndef __Kit_H__
#define __Kit_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT const int64_t KitAWS;
FOUNDATION_EXPORT const int64_t KitKYC;
FOUNDATION_EXPORT const int64_t KitMOMENT;
FOUNDATION_EXPORT const int64_t KitPAY;

FOUNDATION_EXPORT NSString* _Nonnull KitGenWsKey(NSString* _Nullable apiKey, NSString* _Nullable devId, int64_t timestamp);

FOUNDATION_EXPORT NSString* _Nonnull KitKeyDecode(NSString* _Nullable src, int64_t timestamp, long bizType);

FOUNDATION_EXPORT NSString* _Nonnull KitPwdEncode(NSString* _Nullable src, NSString* _Nullable devId, int64_t timestamp);

#endif
