
// Objective-C API for talking to the following Go packages
//
//	kit
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Kit_FRAMEWORK_H__
#define __Kit_FRAMEWORK_H__

#include "Kit.objc.h"
#include "Universe.objc.h"

#endif
